name: Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup git
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git submodule update --init --recursive

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt install -y libgtk-3-dev cmake ninja-build
        cd ..
        git clone https://github.com/petabyt/libui-dev.git --depth 1 --recurse-submodules
        git clone https://github.com/petabyt/libui-scintilla.git --depth 1 --recurse-submodules

    - name: Build everything
      run: cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DRIM_COMPILE_DEMOS=ON -DRIM_COMPILE_LIBUI_SCINTILLA=ON -DRIM_COMPILE_LUA_EDITOR=ON && cmake --build build
